### ISSUE TITLE
Including components crashes vetur?

### ISSUE THREAD

**Issue by ColinTree** [vuejs/vetur#1157]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win
- Vetur version: 0.16.2
- VS Code version: 1.32.3

## Problem

For my project (https://github.com/ColinTree/ListViewGenerator/tree/vetur-crash)
Any definition of components crashes the vetur server, like the following:
![image](https://user-images.githubusercontent.com/22613139/54598998-aa940580-4a74-11e9-9b86-c4968eed9aa1.png)
With log in Output (repeated five times and then vetur stops):

```
Vetur initialized
c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:76414
                throw e;
                ^

TypeError: Cannot read property 'parameters' of undefined
    at inferFromAnnotatedParameters (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:42311:33)
    at checkFunctionExpressionOrObjectLiteralMethod (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:42652:33)
    at checkObjectLiteralMethod (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:43527:38)
    at checkObjectLiteral (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:39381:32)
    at checkExpressionWorker (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:43645:28)
    at checkExpression (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:43593:42)
    at checkExpressionForMutableLocation (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:43505:24)
    at checkPropertyAssignment (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:43516:20)
    at checkObjectLiteral (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:39378:32)
    at checkExpressionWorker (c:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\server\node_modules\typescript\lib\typescript.js:43645:28)
[Info  - 下午6:23:26] Connection to server got closed. Server will restart.
[Error - 下午6:23:26] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-languageclient\lib\client.js:2150:42)
	at LanguageClient.handleConnectionClosed (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-languageclient\lib\main.js:150:15)
	at closeHandler (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-languageclient\lib\client.js:2137:18)
	at CallbackList.invoke (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at ChildProcess.EventEmitter.emit (domain.js:442:20)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
[Error - 下午6:23:26] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\main.js:876:25)
	at Object.dispose (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-languageclient\lib\client.js:71:35)
	at LanguageClient.handleConnectionClosed (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-languageclient\lib\client.js:2150:42)
	at LanguageClient.handleConnectionClosed (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-languageclient\lib\main.js:150:15)
	at closeHandler (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-languageclient\lib\client.js:2137:18)
	at CallbackList.invoke (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at closeHandler (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\main.js:226:26)
	at CallbackList.invoke (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\events.js:120:36)
	at IPCMessageReader.fireClose (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.constructor.eventEmitter.on (C:\Users\50247\.vscode\extensions\octref.vetur-0.16.2\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:187:15)
	at ChildProcess.EventEmitter.emit (domain.js:442:20)
	at maybeClose (internal/child_process.js:961:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
```

## Reproducible Case

See screen record gif

![video](https://user-images.githubusercontent.com/22613139/54600534-f300f280-4a77-11e9-9d5c-e87406e9ea5e.gif)

**Comment by ColinTree** [comment]
The same crash happened when I press ctrl and move my mouse on `.vue` file imports

**Comment by ColinTree** [comment]
Should I fully migrate to typescript, like with `vue-component-class`?

**Comment by ColinTree** [comment]
Seems fixed (but I dont know why), closing this.

**Comment by octref** [comment]
It seems this would be an issue fixed by using latest TS version. You can do this:

- `yarn add -D typescript@3.3` in workspace
-  `"vetur.useWorkspaceDependencies": true`
