### ISSUE TITLE
Fix failing diagnostic test

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1194]
https://travis-ci.org/vuejs/vetur/jobs/517934231

```
  45 passing (55s)
  1 failing
  1) Should do codeAction
       finds codeAction for unused import:
      AssertionError [ERR_ASSERTION]: Cannot find matching codeAction with title 'Remove declaration for: 'lodash''
Seen codeActions are:
[]
      + expected - actual
      -false
      +true
      
      at expectedActions.forEach.eAction (test/lsp/codeAction/basic.test.ts:46:12)
      at Array.forEach (<anonymous>)
      at test/lsp/codeAction/basic.test.ts:45:19
      at Generator.next (<anonymous>)
      at fulfilled (dist/test/lsp/codeAction/basic.test.js:4:58)
```

**Comment by octref** [comment]
Seems to no longer showing up.
