### ISSUE TITLE
Eslint crashes vetur 0.18.1

### ISSUE THREAD

**Issue by TimYi** [vuejs/vetur#1216]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Linux
- Vetur version: 0.18.1
- VS Code version: 1.33.1

## Problem

oaded bundled typescript@3.3.4000.
Vetur initialized
/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/eslint/lib/linter.js:906
            throw err;
            ^

TypeError: Cannot read property 'name' of undefined
    at EventEmitter.VAttribute[directive=true][key.name='if'] (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/eslint-plugin-vue/lib/rules/no-use-v-if-with-v-for.js:85:44)
    at EventEmitter.emit (events.js:187:15)
    at NodeEventGenerator.applySelector (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/vue-eslint-parser/index.js:3128:26)
    at NodeEventGenerator.applySelectors (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/vue-eslint-parser/index.js:3142:22)
    at NodeEventGenerator.enterNode (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/vue-eslint-parser/index.js:3150:14)
    at traverse (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/vue-eslint-parser/index.js:110:13)
    at traverse (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/vue-eslint-parser/index.js:117:21)
    at traverse (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/vue-eslint-parser/index.js:122:13)
    at traverse (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/vue-eslint-parser/index.js:117:21)
    at traverse (/home/ytm/.vscode/extensions/octref.vetur-0.18.1/server/node_modules/vue-eslint-parser/index.js:117:21)

![image](https://user-images.githubusercontent.com/7494892/56554223-95eee400-65c3-11e9-89b1-e5ec152fa481.png)

## Reproducible Case

This file will cause vetur crash every time:

[approvePanel.vue.zip](https://github.com/vuejs/vetur/files/3105799/approvePanel.vue.zip)

**Comment by octref** [comment]
Please report this issue to https://github.com/vuejs/eslint-plugin-vue.
