### ISSUE TITLE
Test suite for source map generations

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1218]
- [x] Start discussion on generating .vue sourcemaps; maybe upstream the changes
- [x] Start building up test suite

**Comment by octref** [comment]
@ktsn I'm getting 3 errors for wrong string literal transformation. Do you think we should care or just ignore them? https://github.com/vuejs/vetur/blob/master/server/src/services/typescriptService/test/sourceMap.test.ts#L66

```
1) Source Map generation
       Source Map generation for test/interpolation/fixture/diagnostics/hyphen-attrs.vue:

      AssertionError [ERR_ASSERTION]: Pos 65: ' doesn't map to 382: "
value = 'Test' should map to this.value = "Test"
      + expected - actual

      -'
      +"
      
      at sourceMapNodes.forEach.node (src/services/typescriptService/test/sourceMap.test.ts:57:14)
      at Array.forEach (<anonymous>)
      at filePathToTest (src/services/typescriptService/test/sourceMap.test.ts:47:18)
      at Context.test (src/services/typescriptService/test/sourceMap.test.ts:72:9)

  2) Source Map generation
       Source Map generation for test/interpolation/fixture/diagnostics/object-literal.vue:

      AssertionError [ERR_ASSERTION]: Pos 113: ' doesn't map to 487: "
'string' should map to "string"
      + expected - actual

      -'
      +"
      
      at sourceMapNodes.forEach.node (src/services/typescriptService/test/sourceMap.test.ts:57:14)
      at Array.forEach (<anonymous>)
      at filePathToTest (src/services/typescriptService/test/sourceMap.test.ts:47:18)
      at Context.test (src/services/typescriptService/test/sourceMap.test.ts:72:9)

  3) Source Map generation
       Source Map generation for test/interpolation/fixture/diagnostics/v-on.vue:

      AssertionError [ERR_ASSERTION]: Pos 487: ' doesn't map to 1469: "
test = 'test' should map to this.test = "test"
      + expected - actual

      -'
      +"
      
      at sourceMapNodes.forEach.node (src/services/typescriptService/test/sourceMap.test.ts:57:14)
      at Array.forEach (<anonymous>)
      at filePathToTest (src/services/typescriptService/test/sourceMap.test.ts:47:18)
      at Context.test (src/services/typescriptService/test/sourceMap.test.ts:72:9)
```

**Comment by octref** [comment]
Seems the internal vuejs roadmap has sourcemap on its plan. Anyway we would need to wait until the parser has a public API until we can even start to think about hooking into vue's codegen and getting a correct sourcemap.

**Comment by octref** [comment]
Decided to ignore such failures. It'd take a lot of effort to fix for little gain...
