### ISSUE TITLE
Setup Azure Devops CI

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1266]
So I can run extension tests on Windows.

**Comment by octref** [comment]
@yyx990803 Wondering if you can let me have hook access for this repo. I'm setting up Azure Devops since it's the only CI that can let me run extension tests on Windows.

**Comment by yyx990803** [comment]
I think you already have admin access, does it not work?

**Comment by octref** [comment]
OAuth failed for me but then I tried manually creating personal access tokens, and it worked. Thanks for taking a look!

**Comment by octref** [comment]
Still a few tests to fix, but mostly looking good on Windows...

**Comment by octref** [comment]
When running locally, here are the failing tests:

```
 1) Should find definition
       finds definition for this.msg:

      AssertionError [ERR_ASSERTION]: '/c:/Users/octref/Desktop/vetur/test/lsp/fixture/client/definition/Basic.vue' == '/C:/Users/octref/Desktop/vetur/test/lsp/fixture/client/definition/Basic.vue'
      + expected - actual

      -/c:/Users/octref/Desktop/vetur/test/lsp/fixture/client/definition/Basic.vue
      +/C:/Users/octref/Desktop/vetur/test/lsp/fixture/client/definition/Basic.vue

      at C:\Users\octref\Desktop\vetur\test\lsp\definition\basic.test.ts:45:10
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\definition\basic.test.js:4:58)

  2) Should find definition
       finds definition for lodash:

      AssertionError [ERR_ASSERTION]: '/c:/Users/octref/Desktop/vetur/test/lsp/fixture/node_modules/@types/lodash/index.d.ts' == '/C:/Users/octref/Desktop/vetur/test/lsp/fixture/node_modules/@types/lodash/index.d.ts'
      + expected - actual

      -/c:/Users/octref/Desktop/vetur/test/lsp/fixture/node_modules/@types/lodash/index.d.ts
      +/C:/Users/octref/Desktop/vetur/test/lsp/fixture/node_modules/@types/lodash/index.d.ts

      at C:\Users\octref\Desktop\vetur\test\lsp\definition\basic.test.ts:45:10
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\definition\basic.test.js:4:58)


  3) Should find definition
       finds definition for Vue#data:

      AssertionError [ERR_ASSERTION]: '/c:/Users/octref/Desktop/vetur/test/lsp/fixture/node_modules/vue/types/options.d.ts' == '/C:/Users/octref/Desktop/vetur/test/lsp/fixture/node_modules/vue/types/options.d.ts'
      + expected - actual

      -/c:/Users/octref/Desktop/vetur/test/lsp/fixture/node_modules/vue/types/options.d.ts
      +/C:/Users/octref/Desktop/vetur/test/lsp/fixture/node_modules/vue/types/options.d.ts

      at C:\Users\octref\Desktop\vetur\test\lsp\definition\basic.test.ts:45:10
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\definition\basic.test.js:4:58)


  4) Should find definition
       finds definition for imported Vue files:

      AssertionError [ERR_ASSERTION]: '/c:/Users/octref/Desktop/vetur/test/lsp/fixture/client/definition/Basic.Item.vue' == '/C:/Users/octref/Desktop/vetur/test/lsp/fixture/client/definition/Basic.Item.vue'
      + expected - actual

      -/c:/Users/octref/Desktop/vetur/test/lsp/fixture/client/definition/Basic.Item.vue
      +/C:/Users/octref/Desktop/vetur/test/lsp/fixture/client/definition/Basic.Item.vue

      at C:\Users\octref\Desktop\vetur\test\lsp\definition\basic.test.ts:45:10
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\definition\basic.test.js:4:58)

  5) Should do documentLink
       shows all documentLinks for Basic.vue:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(result.some(l => isEqualLink(l, el)))

      + expected - actual

      -false
      +true

      at expectedLinks.forEach.el (C:\Users\octref\Desktop\vetur\test\lsp\documentLink\basic.test.ts:30:12)
      at Array.forEach (<anonymous>)
      at C:\Users\octref\Desktop\vetur\test\lsp\documentLink\basic.test.ts:29:17
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\documentLink\basic.test.js:4:58)

  6) Should find references
       finds references for this.msg:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(result.some(l => {
  return l.range.isEqual(el.range) && l.uri.path === el.uri.path;
  }))

      + expected - actual

      -false
      +true

      at expectedLocations.forEach.el (C:\Users\octref\Desktop\vetur\test\lsp\references\basic.test.ts:60:12)
      at Array.forEach (<anonymous>)
      at C:\Users\octref\Desktop\vetur\test\lsp\references\basic.test.ts:59:21
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\references\basic.test.js:4:58)

  7) Should find references
       finds references for lodash:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(result.some(l => {
  return l.range.isEqual(el.range) && l.uri.path === el.uri.path;
  }))

      + expected - actual

      -false
      +true

      at expectedLocations.forEach.el (C:\Users\octref\Desktop\vetur\test\lsp\references\basic.test.ts:60:12)
      at Array.forEach (<anonymous>)
      at C:\Users\octref\Desktop\vetur\test\lsp\references\basic.test.ts:59:21
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\references\basic.test.js:4:58)

  8) Should find references
       finds references for Vue#data:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(result.some(l => {
  return l.range.isEqual(el.range) && l.uri.path === el.uri.path;
  }))

      + expected - actual

      -false
      +true

      at expectedLocations.forEach.el (C:\Users\octref\Desktop\vetur\test\lsp\references\basic.test.ts:60:12)
      at Array.forEach (<anonymous>)
      at C:\Users\octref\Desktop\vetur\test\lsp\references\basic.test.ts:59:21
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\references\basic.test.js:4:58)


  9) Should find references
       finds references for imported Vue files:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(result.some(l => {
  return l.range.isEqual(el.range) && l.uri.path === el.uri.path;
  }))

      + expected - actual

      -false
      +true

      at expectedLocations.forEach.el (C:\Users\octref\Desktop\vetur\test\lsp\references\basic.test.ts:60:12)
      at Array.forEach (<anonymous>)
      at C:\Users\octref\Desktop\vetur\test\lsp\references\basic.test.ts:59:21
      at Generator.next (<anonymous>)
      at fulfilled (C:\Users\octref\Desktop\vetur\dist\test\lsp\references\basic.test.js:4:58)
```
