### ISSUE TITLE
Vue Language Server with Sublime Text 3 LSP error

### ISSUE THREAD

**Issue by kat0d** [vuejs/vetur#1396]
Windows 10 x64 LTSC
vue-language-server@0.0.60
Hi, I had already written a question in LSP section https://github.com/tomv564/LSP/issues/681, and I'm really don't know, in which repo I need to send this issue.
All logs and screenshots are here https://github.com/tomv564/LSP/issues/681
It seems a bug with .vue files. Error with ```file.vue``` file, but it's ok with ```file.vue.template```
Please, need help.

**Comment by octref** [comment]
From the linked issue I see it's properly due to improper path handling, `W:\` is normalized to `w:\` and this might have caused TS not able to find it. Probably would be a similar fix as #1348.

**Comment by kat0d** [comment]
full loge from Sublime console
```
DPI mode: per-monitor v2
startup, version: 3207 windows x64 channel: stable
executable: /C/Soft/ST3/sublime_text.exe
working dir: /C/Windows/system32
packages path: /C/Users/zion/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/zion/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Soft/ST3/Packages
zip path: /C/Users/zion/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["All Autocomplete", "Better Less", "ESLint-Formatter", "PHPUnitKit", "SCSS", "SublimeLinter-eslint", "Vintage"]
top level value must be an array
pre session restore time: 0.870528
warning: mnemonic c not found in menu caption CLI
startup time: 0.928528
first paint time: 0.942528
git: tracking working dir W:\www-job\slo-free
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.detect_indentation
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.10-wcwidth
reloading plugin 0_package_control_loader.40-pywinpty
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-dateutil
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-pyte
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-jsonschema
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin A File Icon.plugin
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Breadcrumbs.Breadcrumbs
reloading plugin Chain of Command.chain
reloading plugin Color Highlighter.color_converter
reloading plugin Color Highlighter.color_highlighter
reloading plugin Color Highlighter.color_hover_listener
reloading plugin Color Highlighter.color_scheme
reloading plugin Color Highlighter.color_scheme_color_highlighter
reloading plugin Color Highlighter.color_searcher
reloading plugin Color Highlighter.color_selection_listener
reloading plugin Color Highlighter.colors
reloading plugin Color Highlighter.content_listener
reloading plugin Color Highlighter.convert_color_command
reloading plugin Color Highlighter.css_colors
reloading plugin Color Highlighter.dummy_event_listener
reloading plugin Color Highlighter.gutter_icons_color_highlighter
reloading plugin Color Highlighter.load_resource
reloading plugin Color Highlighter.main
reloading plugin Color Highlighter.path
reloading plugin Color Highlighter.phantoms_color_highlighter
reloading plugin Color Highlighter.pick_color_command
reloading plugin Color Highlighter.regex_compiler
reloading plugin Color Highlighter.regions
reloading plugin Color Highlighter.set_setting_command
reloading plugin Color Highlighter.settings
reloading plugin Color Highlighter.st_helper
reloading plugin Color Highlighter.topsort
reloading plugin CSS3.css3_completions
reloading plugin CSS3.rgb_to_hex
reloading plugin Diffy.diffy
reloading plugin Emmet.emmet-plugin
reloading plugin Hover Image Preview.main
reloading plugin HTML5.encode_html_entities
reloading plugin HTML5.html_completions
reloading plugin ImageMagick.SublimeMagick
reloading plugin Jump Along Indent.file_scanner
reloading plugin Jump Along Indent.jump_along_indent
reloading plugin Jump Along Indent.view_helper
reloading plugin Laravel 5 Artisan.Laravel 5 Artisan
reloading plugin Laravel Blade AutoComplete.BladeAutoComplete
reloading plugin LESS.less_completions
reloading plugin LSP.boot
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin PackageResourceViewer.package_resource_viewer
reloading plugin PackageResourceViewer.package_resources
reloading plugin ProjectManager.json_file
reloading plugin ProjectManager.project_manager
reloading plugin Reindent on save.ReindentOnSave
reloading plugin Sass.sass_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin Stylus.Stylus
reloading plugin SublimeLinter-php.linter
reloading plugin SublimeLinter.__init__
reloading plugin SublimeLinter.active_linters_view
reloading plugin SublimeLinter.busy_indicator_view
reloading plugin SublimeLinter.goto_commands
reloading plugin SublimeLinter.highlight_view
reloading plugin SublimeLinter.log_handler
reloading plugin SublimeLinter.message_view
reloading plugin SublimeLinter.panel_view
reloading plugin SublimeLinter.status_bar_view
reloading plugin SublimeLinter.sublime_linter
reloading plugin SublimeServer.SublimeServer
reloading plugin Sync View Scroll.syncscroll
reloading plugin Autoprefixer.Autoprefixer
reloading plugin Autoprefixer.node_bridge
reloading plugin ColorPicker.sublimecp
reloading plugin CSScomb.CSScomb
reloading plugin Gulp.base_command
reloading plugin Gulp.caches
reloading plugin Gulp.cross_platform_codecs
reloading plugin Gulp.cross_platform_process
reloading plugin Gulp.dir_context
reloading plugin Gulp.event_task
reloading plugin Gulp.gulp
reloading plugin Gulp.gulp_version
reloading plugin Gulp.hasher
reloading plugin Gulp.insert_in_output_view
reloading plugin Gulp.plugins
reloading plugin Gulp.progress_notifier
reloading plugin Gulp.settings
reloading plugin Gulp.status_bar
reloading plugin Gulp.timeout
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin JavaScript Completions._generated_2018_02_11_at_20_21_24
reloading settings Packages/User/SublimeServer.sublime-settings
reloading plugin JavaScript Completions.reloader
reloading plugin JsPrettier.JsPrettier
reloading plugin LSP-css.plugin
reloading plugin LSP-html.plugin
reloading plugin LSP-vue.plugin
reloading plugin Minify.Minify
reloading plugin PlainTasks.APlainTasksCommon
reloading plugin PlainTasks.PlainTasks
reloading plugin PlainTasks.PlainTasksDates
reloading plugin PlainTasks.PlainTasksToHTML
reloading plugin PlainTasks.plist_parser
reloading plugin SideBarGit.SideBarAPI
reloading plugin SideBarGit.SideBarGit
reloading plugin SideBarGit.SideBarGitCommands
reloading plugin StringUtilities.stringutilities
reloading plugin SublimeCodeIntel.ordereddict
reloading plugin SublimeCodeIntel.SublimeCodeIntel
reloading plugin Terminus.main
reloading plugin TodoReview.TodoReview
reloading plugin User.example
plugins loaded
LSP: received config lsp-css from LspCssPlugin
LSP: received config lsp-html from LspHtmlPlugin
LSP: received config lsp-vue from LspVuePlugin
LSP: global configs ['lsp-vue=True', 'lsp-css=True', 'lsp-html=True', 'clangd=False', 'lsp-tsserver=True', 'metals=False', 'dart=False', 'golsp=False', 'reason=False', 'bashls=False', 'javascript-typescript-langserver=True', 'rls=False', 'ruby=False', 'phpls=False', 'polymer-ide=False', 'flow=False', 'ocaml=False', 'vscode-css=False', 'intelephense-ls=True', 'typescript-language-server=False', 'gopls=False', 'eslint=False', 'pyls=False', 'cquery=False', 'jdtls=False', 'ra-lsp=False', 'haskell-ide-engine=False']
LSP: window 2 starting 1 initial views
syncScroll starting
LSP-css: Server is installed.
LSP-html: Server is installed.
LSP-vue: Server is installed.
Emmet: No need to update PyV8
reloading settings Packages/User/SublimeServer.sublime-settings
Exception in thread DownloadCanIuseJsonData:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\JavaScript Completions\_generated_2018_02_11_at_20_21_24.py", line 784, in donwload_can_i_use_json_data
    os.remove(path_to_test_can_i_use_data)
PermissionError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Users\\zion\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Completions\\helper\\can_i_use\\can_i_use_data2.json'

Package Control: Skipping automatic upgrade, last run at 2019-08-21 20:28:16, next run at 2019-08-21 21:28:16 or after
LSP: window 2 requests lsp-vue for W:\www-job\slo-free\src\views\Rules.vue
LSP: starting in W:\www-job\slo-free
LSP: starting ['node', 'C:\\Users\\zion\\AppData\\Roaming\\Sublime Text 3\\Packages\\LSP-vue\\node_modules\\vue-language-server\\bin\\vls']
LSP:  --> initialize
LSP: window 2 added session lsp-vue
lsp-vue: Loaded bundled typescript@3.5.3.
lsp-vue: Vetur initialized
LSP:      {'capabilities': {'referencesProvider': True, 'documentSymbolProvider': True, 'definitionProvider': True, 'hoverProvider': True, 'documentFormattingProvider': False, 'textDocumentSync': 1, 'colorProvider': True, 'documentHighlightProvider': True, 'documentLinkProvider': {'resolveProvider': False}, 'completionProvider': {'resolveProvider': True, 'triggerCharacters': ['.', ':', '<', '"', "'", '/', '@', '*']}, 'codeActionProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(']}}}
LSP:  --> initialized
LSP:  --> textDocument/didOpen
P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\typescript\lib\typescript.js:122217:
throw new Error("Could not find sourceFile: '" + fileName + "' in " + (program && JSON.stringify(program.getSourceFiles().map(function (f) { return f.fileName; }))) + ".");:
^:
:
Error: Could not find sourceFile: 'w:\www-job\slo-free\src\views\Rules.vue.template' in ["P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es5.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2016.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2017.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2018.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.dom.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.core.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.collection.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.generator.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.iterable.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.promise.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.proxy.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.reflect.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.symbol.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2016.array.include.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2017.object.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2017.string.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2017.intl.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2018.asynciterable.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2018.intl.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2018.promise.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.es2018.regexp.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.esnext.intl.d.ts","P:/Users/zion/AppData/Roaming/Sublime Text 3/Packages/LSP-vue/node_modules/typescript/lib/lib.esnext.bigint.d.ts","W:/www-job/slo-free/src/views/Rules.vue","W:/www-job/slo-free/node_modules/vue/types/vnode.d.ts","W:/www-job/slo-free/node_modules/vue/types/options.d.ts","W:/www-job/slo-free/node_modules/vue/types/plugin.d.ts","W:/www-job/slo-free/node_modules/vue/types/vue.d.ts","W:/www-job/slo-free/node_modules/vue/types/index.d.ts","vue-temp/vue-editor-bridge.ts","W:/www-job/slo-free/src/views/Rules.vue.template","W:/www-job/slo-free/node_modules/@types/events/index.d.ts","W:/www-job/slo-free/node_modules/@types/node/globals.d.ts","W:/www-job/slo-free/node_modules/@types/node/assert.d.ts","W:/www-job/slo-free/node_modules/@types/node/async_hooks.d.ts","W:/www-job/slo-free/node_modules/@types/node/buffer.d.ts","W:/www-job/slo-free/node_modules/@types/node/child_process.d.ts","W:/www-job/slo-free/node_modules/@types/node/cluster.d.ts","W:/www-job/slo-free/node_modules/@types/node/console.d.ts","W:/www-job/slo-free/node_modules/@types/node/constants.d.ts","W:/www-job/slo-free/node_modules/@types/node/crypto.d.ts","W:/www-job/slo-free/node_modules/@types/node/dgram.d.ts","W:/www-job/slo-free/node_modules/@types/node/dns.d.ts","W:/www-job/slo-free/node_modules/@types/node/domain.d.ts","W:/www-job/slo-free/node_modules/@types/node/events.d.ts","W:/www-job/slo-free/node_modules/@types/node/fs.d.ts","W:/www-job/slo-free/node_modules/@types/node/http.d.ts","W:/www-job/slo-free/node_modules/@types/node/http2.d.ts","W:/www-job/slo-free/node_modules/@types/node/https.d.ts","W:/www-job/slo-free/node_modules/@types/node/inspector.d.ts","W:/www-job/slo-free/node_modules/@types/node/module.d.ts","W:/www-job/slo-free/node_modules/@types/node/net.d.ts","W:/www-job/slo-free/node_modules/@types/node/os.d.ts","W:/www-job/slo-free/node_modules/@types/node/path.d.ts","W:/www-job/slo-free/node_modules/@types/node/perf_hooks.d.ts","W:/www-job/slo-free/node_modules/@types/node/process.d.ts","W:/www-job/slo-free/node_modules/@types/node/punycode.d.ts","W:/www-job/slo-free/node_modules/@types/node/querystring.d.ts","W:/www-job/slo-free/node_modules/@types/node/readline.d.ts","W:/www-job/slo-free/node_modules/@types/node/repl.d.ts","W:/www-job/slo-free/node_modules/@types/node/stream.d.ts","W:/www-job/slo-free/node_modules/@types/node/string_decoder.d.ts","W:/www-job/slo-free/node_modules/@types/node/timers.d.ts","W:/www-job/slo-free/node_modules/@types/node/tls.d.ts","W:/www-job/slo-free/node_modules/@types/node/trace_events.d.ts","W:/www-job/slo-free/node_modules/@types/node/tty.d.ts","W:/www-job/slo-free/node_modules/@types/node/url.d.ts","W:/www-job/slo-free/node_modules/@types/node/util.d.ts","W:/www-job/slo-free/node_modules/@types/node/v8.d.ts","W:/www-job/slo-free/node_modules/@types/node/vm.d.ts","W:/www-job/slo-free/node_modules/@types/node/worker_threads.d.ts","W:/www-job/slo-free/node_modules/@types/node/zlib.d.ts","W:/www-job/slo-free/node_modules/@types/node/base.d.ts","W:/www-job/slo-free/node_modules/@types/node/ts3.2/util.d.ts","W:/www-job/slo-free/node_modules/@types/node/ts3.2/globals.d.ts","W:/www-job/slo-free/node_modules/@types/node/ts3.2/index.d.ts","W:/www-job/slo-free/node_modules/@types/minimatch/index.d.ts","W:/www-job/slo-free/node_modules/@types/glob/index.d.ts","W:/www-job/slo-free/node_modules/@types/normalize-package-data/index.d.ts","W:/www-job/slo-free/node_modules/@types/q/index.d.ts"].:
at getValidSourceFile (P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\typescript\lib\typescript.js:122217:23):
at Object.getSemanticDiagnostics (P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\typescript\lib\typescript.js:122419:36):
at VueInterpolationMode.doValidation (P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\vue-language-server\dist\modes\template\interpolationMode.js:38:56):
at VueHTMLMode.doValidation (P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\vue-language-server\dist\modes\template\index.js:21:86):
at languageModes.getAllLanguageModeRangesInDocument.forEach.lmr (P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\vue-language-server\dist\services\vls.js:358:51):
at Array.forEach (<anonymous>):
at VLS.doValidate (P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\vue-language-server\dist\services\vls.js:356:72):
at VLS.validateTextDocument (P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\vue-language-server\dist\services\vls.js:350:34):
at Timeout.pendingValidationRequests.(anonymous function).setTimeout [as _onTimeout] (P:\Users\zion\AppData\Roaming\Sublime Text 3\Packages\LSP-vue\node_modules\vue-language-server\dist\services\vls.js:339:18):
at listOnTimeout (internal/timers.js:535:17):
LSP:LSP: LSP stdout process ended.
 LSP stream logger stopped.
LSP:  --> textDocument/codeAction
Failure writing to stdout
Traceback (most recent call last):
  File "C:\Users\zion\AppData\Roaming\Sublime Text 3\Installed Packages\LSP.sublime-package\plugin/core/transports.py", line 227, in write_stdin
    self.process.stdin.flush()
OSError: [Errno 22] Invalid argument

LSP: transport failed
```

**Comment by octref** [comment]
On macOS this doesn't happen though. `Rules.vue.template` is a virtual file that should only live in memory. There's a path check that guaranteed `Rules.vue.template` to be available to the TS language server, but that path check failed for Windows.

**Comment by octref** [comment]
I'll need some time to sort out Windows CI https://github.com/vuejs/vetur/pull/1376 and fix https://github.com/vuejs/vetur/issues/1266#issuecomment-490295222.

**Comment by kat0d** [comment]
Currently, I'm working with Vue on a VSCode, and there it's all fine with Vetur.
