### ISSUE TITLE
VTI feedback thread

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1635]
VTI (Vetur Terminal Interface) is available since 0.23.0.

It's not very well tested. I don't have the bandwidth to test it in real world projects.

Formatting can be done, but I'm not sure what config to prefer.

Anyway, this surfaces Vetur's interpolation service's errors onto CLI. When this becomes stable enough, it can help people catch errors currently uncatchable by Vue's compiler or Webpack.

**Comment by cexbrayat** [comment]
@octref Thank you for taking the time to do this!

It looks like it also goes through `node_modules` resulting in false positive for a Vue CLI project that uses the router.

Repro:

```
npx -p @vue/cli@next vue create vetur-router --inlinePreset '{"useConfigFiles": true,"plugins": {"@vue/cli-plugin-typescript": {"classComponent": false}, "@vue/cli-plugin-router": {}}}'
cd vetur-router
vti diagnostics
```

Throws:
```
Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind. /Users/ced-pro/Code/test/vue-cli-tests/vetur-router/node_modules/@vue/cli-plugin-router/generator/template/src/views/About.vue.template
    at Object.assertEqual (/usr/local/lib/node_modules/vti/node_modules/typescript/lib/typescript.js:2109:17)
    at getOrCreateSourceFileByPath (/usr/local/lib/node_modules/vti/node_modules/typescript/lib/typescript.js:131217:34)
```

**Comment by octref** [comment]
@cexbrayat I can repro it. Opened #1639. For bugs please use new issue.

**Comment by goldingdamien** [comment]
How can this be used on a whole Vue project? Or a Nuxt project?

**Comment by goldingdamien** [comment]
"any" error with text "Property '...' does not exist on type 'object'.Vetur(2339)" not being outputted. Please check.

**Comment by octref** [comment]
@goldingdamien If you have bugs, please make a [https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md](repro case) and open a new issue.

**Comment by mesqueeb** [comment]
@octref Will it be possible to catch type errors for the props of another component?

Eg. something like:
```vue
<template>
  <MyComponent date="2019" />
</template>
```
> MyComponent.date must be a valid `Date` object

So to have VTI check the type of the prop of the underlying component which are defined like so:

```
props: {
  date: Object as PropType<Date>
}
```

**Comment by yoyo930021** [comment]
> @octref Will it be possible to catch type errors for the props of another component?
> 
> Eg. something like:
> 
> ```
> <template>
>   <MyComponent date="2019" />
> </template>
> ```
> 
> > MyComponent.date must be a valid `Date` object
> 
> So to have VTI check the type of the prop of the underlying component which are defined like so:
> 
> ```ts
> props: {
>   date: Object as PropType<Date>
> }
> ```

https://github.com/vuejs/vetur/issues/1596

**Comment by shameleo** [comment]
Is it already supposed to work with Vue 3? I've not able to get any relevant result. Here is my setup (look readme): https://github.com/shameleo/vue-next-test/tree/f1ed6946ec92b6678cb835465db86926bda06775

**Comment by jackkoppa** [comment]
Thanks so much for doing this, @octref. This is going to be huge for us when it's stable.

I'm currently seeing the same issue that @ktsn has opened here: #1699 
Both on our production apps - which are a similar size to what they mention (100+ .vue, 50+ .ts) - and also on this [much smaller app](https://github.com/jackkoppa/vueconf-2020-typescript-at-politico), with only 8 files under test.

I'll try to open a simplified, reliable repro rep

**Comment by odanado** [comment]
I get an error.
`Error: Cannot find module 'vscode-css-languageservice/lib/umd/data/browsers'`

reproduction repository: https://github.com/odan-sandbox/vti-error-reproduction

**Comment by ktsn** [comment]
@odanado Could you open a new issue for a bug report? (my navigation on twitter was probably misleading, sorry!)

**Comment by odanado** [comment]
@ktsn Sorry.
I created #1732

**Comment by harvey-woo** [comment]
In my case, vti stop when invoke ```clientConnection.sendRequest('$/getDiagnostics')``` without any error

**Comment by yoyo930021** [comment]
> In my case, vti stop when invoke ```clientConnection.sendRequest('$/getDiagnostics')``` without any error
> 
> ![image](https://user-images.githubusercontent.com/2538123/80217076-ab349d80-8671-11ea-95f2-6018b46ade25.png)
> ![image](https://user-images.githubusercontent.com/2538123/80217096-b25bab80-8671-11ea-82cc-96445653b90b.png)
> 

#1805 will fix.

**Comment by rfox12** [comment]
After spending very many hours on "my utlimate Vue setup" I've found that JS/TS errors in the <templates> is really the missing ingredient for me.  I *want* to see error 2339 when a developer references an attribute that does not exist!  I think VTI may be the key.  Thanks for all the hard work on this (and Vetur).  

Two quick questions:
1) Is the plan to also incorporate this into the "Problems" area of VSCode--that would be nice. 
2) I haven't really used much Typescript in the <template>, but will vti be equally good at handling TS and JS format?

**Comment by octref** [comment]
> Is the plan to also incorporate this into the "Problems" area of VSCode--that would be nice.

You can turn it on with `vetur.experimental.templateInterpolationService`.

> I haven't really used much Typescript in the template section, but will vti be equally good at handling TS and JS format?

I don't think you can use TS in template interpolations without extra setup.

**Comment by andrewisaburden** [comment]
`vue-cli` seems to use `codeframe` for formatting ESLint errors by default. VTI could use the same.

What kind of use-cases do you have in mind for VTI? I think it would be very useful along with a lint step in CI/build pipelines, for example.

The docs [here](https://github.com/vuejs/vetur/wiki/Developing-Language-Server-Features) don't seem to quite contain enough information for me to easily figure out how to run a debugger on VLS when running `vti diagnostics`. It could be useful to explain a little more somewhere.

I have some ideas for minor improvements and contributions. Is creating an issue the best way to propose changes?

**Comment by octref** [comment]
@andrewisaburden I use `console.log` to debug VTI. I haven't looked into how to set it up with a debugger. Opening new issues is definitely the best way to propose changes.

**Comment by P4sca1** [comment]
Thanks for making `vti`, it is very helpful!
It would be even more helpful, if line numbers could be shown for each error.

**Comment by lzxb** [comment]
Me too.

**Comment by soerenmartius** [comment]
At the moment it seems that the `vti diagnostics` command only accepts directories as an argument? 
E.g., running `vti diagnostics src/components/` will check all `.vue` inside the src/components directory. Passing a single file as an argument results in an `ENOTDIR` exception. It would be helpful to pass single files or a list of single files also use vti with pre-commit hooks also.

**Comment by yoyo930021** [comment]
> At the moment it seems that the `vti diagnostics` command only accepts directories as an argument?
> E.g., running `vti diagnostics src/components/` will check all `.vue` inside the src/components directory. Passing a single file as an argument results in an `ENOTDIR` exception. It would be helpful to pass single files or a list of single files also use vti with pre-commit hooks also.

You can open a new issue on it. ^_^

**Comment by soerenmartius** [comment]
> > At the moment it seems that the `vti diagnostics` command only accepts directories as an argument?
> > E.g., running `vti diagnostics src/components/` will check all `.vue` inside the src/components directory. Passing a single file as an argument results in an `ENOTDIR` exception. It would be helpful to pass single files or a list of single files also use vti with pre-commit hooks also.
> 
> You can open a new issue on it. ^_^

Sure

**Comment by bertvanbrakel** [comment]
Very cool tool. I'm wondering if it would be possible to accept a flag to only show errors on failure. and otherwise just be silent? I'd liked to incorporate this into my npm build (as a pre-commit hook using 'shared-git-hhok') and currently it spams the console.

Maybe a flat '--errors-only' or '--log-level DEBUG/INFO/WARN/ERROR ? The latter allowing more room for printing diagnostics if required.

Many thanks for building this tool

**Comment by andrewisaburden** [comment]
@bertvanbrakel I think this will be solved with #2451

**Comment by Spaubleit** [comment]
When I use VTI with css modules I always get same errors:
```
Error: Property '$style' does not exist on type 'CombinedVueInstance<...>
  1 | <template>
> 2 |   <div :class="['main', $style.event]">
    |                         ^^^^^^
```

**Comment by ChristianBirkl** [comment]
We've enabled it in a medium sized project (currently 300+ .vue files) and I can't live without it!

That said - some features i'd like to see:

- Be able to exclude specific files (e.g. !glob filters on the command line or something vti.config.json file)
- Specify warn as error (I can't seem to find any switch to set warn to error (e.g. missing props)
- I've tried to integrate it in the vite rollup chain in order to get validation errors in the browser - but $/getDiagnostics seems to cache the file - any chance to invalidate the cached version?

**Comment by Juice10** [comment]
I'm using vue 2 and have a mix of typescript and none typescript components. I'd love to be able to tell vti to ignore my plain javascript components.
Otherwise it spits out reams of errors like these:
```
Error: Property 'isLoading' does not exist on type 'CombinedVueInstance<Record<never, any> & Vue, object, object, object, Record<never, any>>'.
  261 |     <PlayerDebugger
  262 |       v-if="showDebugger"
> 263 |       :is-loading="isLoading"
      |                    ^^^^^^^^^
  264 |       :is-playing="isPlaying"
  265 |       :video-id="video.id"
  266 |       :current-action-id="currentActionId"
```

**Comment by snake-py** [comment]
Hey pretty cool package, I have trouble to set it up correctly, if anyone could perhaps provide some guidance. 

I have installed it globally, now in vscode I have enabled template interpolation. Now I am going into a file without any type errors and copy the relative path. When I am running now:

```bash
vti diagnostics -l ERROR  . src/components/widgets/compopnenWithoutErrors.vue
```

I am getting something like this: 

```
Error: 'this' implicitly has type 'any' because it does not have a type annotation.
  118 |           </button>
  119 |           <button v-else type="button" class="btn btn-secondary" v-on:click="stopIdle()">
> 120 |             {{ $t('notification.modal.button.close.on.fallback') }}
      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 121 |           </button>
      | ^^^^^^^^^^^^^^^^^^^
> 122 |         </div>
``` 

SO it is basically showing me that there are errors, but if I check manually I do not see any error.

**Comment by Popeye4242** [comment]
I don't know if vti ist still relevant but from my experience its setup is too hard to be worth it. 

`'this' implicitly has type 'any' because it does not have a type annotation.`
`Cannot find name '__vlsComponentData'.`
`Cannot find name '__vlsComponentHelper'.`

This are issues that every single user would face but it is not documented how to resolve them. So vetur is useless as its just highlighting every single line in vue files.

**Comment by snake-py** [comment]
@Popeye4242 I essentially gave up on the issue as well.

**Comment by kije** [comment]
I've ran in to an issue with the following code, where vti doesn't seem to pick up the correct type for `processingProgress` (should allow `null`, but VTI insists that it only can be `number | undefined`)

```console
Error: Type 'number | null' is not assignable to type 'number | undefined'.
  Type 'null' is not assignable to type 'number | undefined'.
  4 |       <DropZone
  5 |         :processing="importProgress !== null || isLoading"
> 6 |         :processingProgress="importProgress"
    |          ^^^^^^^^^^^^^^^^^^
  7 |         :limit="1"
  8 |         :error.sync="dropzoneError"
```

```ts
  private get importProgress(): number | null {
    const uploadRange = 85;

    if (this.uploadProgress === null) {
      return null;
    }

    return (uploadRange / 100) * this.uploadProgress;
  }
```

DropZone.vue:
```ts
@Component({
  components: { ProgressBar, WithDragAndDrop, LoadingIndicator },
})
export default class DropZone extends Vue {
  // ... other props

  @Prop({ default: null, type: Number, required: false })
  private readonly processingProgress: number | null;
```
