### ISSUE TITLE
VTI crashes for *.vue files in node_modules

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#1639]
Repro:

```bash
npx -p @vue/cli@next vue create vetur-router --inlinePreset '{"useConfigFiles": true,"plugins": {"@vue/cli-plugin-typescript": {"classComponent": false}, "@vue/cli-plugin-router": {}}}'
cd vetur-router
vti diagnostics
```

```
/Users/pine/.nvm/versions/node/v10.14.1/lib/node_modules/vti/node_modules/typescript/lib/typescript.js:2137
            throw e;
            ^

Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind. /Users/pine/Code/mine/vetur/vetur-router/node_modules/@vue/cli-plugin-router/generator/template/src/views/About.vue.template
```

**Comment by kapitanluffy** [comment]
```
:: --> lsp-vue initialize(1): {'initializationOptions': {'config': {'typescript': {'format': {}}, 'html': {'suggest': {}}, 'vetur': {'completion': {'autoImport': False, 'useScaffoldSnippets': False, 'tagCasing': 'kebab'}, 'validation': {'style': True, 'script': True, 'template': True}, 'useWorkspaceDependencies': False, 'format': {'defaultFormatter': {'ts': 'none', 'js': 'none'}, 'enable': True, 'defaultFormatterOptions': {}, 'styleInitialIndent': False, 'scriptInitialIndent': False, 'options': {'useTabs': False, 'tabSize': 4}}, 'experimental': {'templateInterpolationService': True}}, 'javascript': {'format': {}}, 'stylusSupremacy': {}, 'emmet': {}, 'css': {}}}, 'capabilities': {'experimental': {}, 'window': {'workDoneProgress': True}, 'workspace': {'configuration': True, 'symbol': {'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'applyEdit': True, 'executeCommand': {}, 'workspaceFolders': True, 'didChangeConfiguration': {'dynamicRegistration': True}, 'workspaceEdit': {'failureHandling': 'abort', 'documentChanges': True}}, 'textDocument': {'documentSymbol': {'hierarchicalDocumentSymbolSupport': True, 'dynamicRegistration': True, 'symbolKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}}, 'hover': {'contentFormat': ['markdown', 'plaintext'], 'dynamicRegistration': True}, 'references': {'dynamicRegistration': True}, 'implementation': {'linkSupport': True, 'dynamicRegistration': True}, 'completion': {'completionItem': {'snippetSupport': True}, 'dynamicRegistration': True, 'completionItemKind': {'valueSet': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}}, 'declaration': {'linkSupport': True, 'dynamicRegistration': True}, 'rename': {'dynamicRegistration': True}, 'colorProvider': {'dynamicRegistration': True}, 'publishDiagnostics': {'relatedInformation': True}, 'synchronization': {'didSave': True, 'willSave': True, 'dynamicRegistration': True, 'willSaveWaitUntil': True}, 'typeDefinition': {'linkSupport': True, 'dynamicRegistration': True}, 'definition': {'linkSupport': True, 'dynamicRegistration': True}, 'signatureHelp': {'signatureInformation': {'parameterInformation': {'labelOffsetSupport': True}, 'documentationFormat': ['markdown', 'plaintext']}, 'dynamicRegistration': True}, 'codeAction': {'codeActionLiteralSupport': {'codeActionKind': {'valueSet': []}}, 'dynamicRegistration': True}, 'rangeFormatting': {'dynamicRegistration': True}, 'documentHighlight': {'dynamicRegistration': True}, 'formatting': {'dynamicRegistration': True}}}, 'rootPath': 'v:\\bidding-site', 'clientInfo': {'name': 'Sublime Text LSP', 'version': '0.10.1'}, 'processId': 231416, 'workspaceFolders': [{'name': 'bidding-site', 'uri': 'file:///V:/bidding-site'}, {'name': 'drivers', 'uri': 'file:///V:/bidding-site/www/modules/bidding/drivers'}, {'name': 'system', 'uri': 'file:///V:/bidding-site/www/foundry/system'}, {'name': 'frontend', 'uri': 'file:///V:/bidding-site/www/themes/bidding/frontend'}, {'name': 'backend', 'uri': 'file:///V:/bidding-site/www/themes/bidding/backend'}], 'rootUri': 'file:///V:/bidding-site'}
lsp-vue: Loaded bundled typescript@3.9.5.
lsp-vue: Vetur initialized
:: <<< lsp-vue 1: {'capabilities': {'codeActionProvider': True, 'documentLinkProvider': {'resolveProvider': False}, 'completionProvider': {'triggerCharacters': ['.', ':', '<', '"', "'", '/', '@', '*'], 'resolveProvider': True}, 'colorProvider': True, 'referencesProvider': True, 'definitionProvider': True, 'documentHighlightProvider': True, 'documentFormattingProvider': False, 'textDocumentSync': 1, 'documentSymbolProvider': True, 'signatureHelpProvider': {'triggerCharacters': ['(']}, 'hoverProvider': True}}
::  -> lsp-vue initialized: {}
::  -> lsp-vue textDocument/didOpen
lsp-vue: D:\~\bin\vetur\server\node_modules\typescript\lib\typescript.js:2251
lsp-vue: throw e;
lsp-vue: ^
lsp-vue: 
lsp-vue: Error: Debug Failure. Expected 3 === 1. Registered script kind should match new script kind.
lsp-vue: at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (D:\~\bin\vetur\server\node_modules\typescript\lib\typescript.js:139326:34)
lsp-vue: at tryReuseStructureFromOldProgram (D:\~\bin\vetur\server\node_modules\typescript\lib\typescript.js:100516:28)
lsp-vue: at Object.createProgram (D:\~\bin\vetur\server\node_modules\typescript\lib\typescript.js:100099:30)
```

I am currently having this issue when using vls.

**Comment by octref** [comment]
@kapitanluffy Please open a new issue then. This is about VTI, not VLS.
It might be that your TS version is too new, and we haven't updated the integration code...

**Comment by kapitanluffy** [comment]
@octref is there a way to downgrade the TS version? Is 3.9.5 too new? I assume that it has a bundled TS version as seen on the logs. 
```
lsp-vue: Loaded bundled typescript@3.9.5.
```
I also checked it in the server's node_modules.

![image](https://user-images.githubusercontent.com/485799/85397628-787e2700-b586-11ea-8e99-534572689074.png)
