### ISSUE TITLE
Vue Language Server crash in 0.23.0

### ISSUE THREAD

**Issue by thislooksfun** [vuejs/vetur#1656]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macOS
- Vetur version: 0.23.0
- VS Code version: 1.41.1

## Problem

Opening any `.vue` file results in the error "The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

Stacktrace:
```
Loaded bundled typescript@3.7.3.
Vetur initialized
[Error - 5:54:02 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Debug Failure. Expected -294 >= 0
  Code: -32603 
/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:2137
            throw e;
            ^

Error: Debug Failure. Expected -294 >= 0
    at Object.assertGreaterThanOrEqual (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:2127:17)
    at createFileDiagnostic (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:16743:18)
    at addProgramDiagnosticAtRefPath (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:97119:64)
    at checkSourceFilesBelongToPath (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:96810:25)
    at getCommonSourceDirectory (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:95285:40)
    at verifyCompilerOptions (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:97019:27)
    at Object.createProgram (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:95257:9)
    at synchronizeHostData (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:131138:26)
    at Object.getProgram (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/node_modules/typescript/lib/typescript.js:131230:13)
    at languageServiceIncludesFile (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/server/dist/modes/script/javascript.js:702:24)
[Info  - 5:54:02 PM] Connection to server got closed. Server will restart.
[Error - 5:54:02 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-languageclient/lib/client.js:2167:42)
	at LanguageClient.handleConnectionClosed (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-languageclient/lib/main.js:152:15)
	at closeHandler (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-languageclient/lib/client.js:2154:18)
	at CallbackList.invoke (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 5:54:02 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-languageclient/lib/client.js:2167:42)
	at LanguageClient.handleConnectionClosed (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-languageclient/lib/main.js:152:15)
	at closeHandler (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-languageclient/lib/client.js:2154:18)
	at CallbackList.invoke (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/Users/tlf/.vscode/extensions/octref.vetur-0.23.0/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:205:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

## Reproducible Case

1. Install v0.23.0
2. Open any .vue file

**Comment by adndyxu** [comment]
0.23.0 can not work in windows successfully,only has highlight, and  without format and hint
solution: roll back to 0.22

**Comment by Galileo01** [comment]
0.23.0 ，CPU usage is too high when editing vue files，around 25%.And when i am coding,only has hightlight ,without hint

**Comment by oskarkunik** [comment]
Not sure if it's connected to #1449 (closed), but type checking in .vue files doesn't work for me in 0.23.0. It's fine when downgraded to 0.22.6. I use linux.

**Comment by SunshowerC** [comment]
same here

**Comment by octref** [comment]
Your issue is closed because you did not provide a repro case. Please read https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md and open a new issue.
