### ISSUE TITLE
crashing in code insiders

### ISSUE THREAD

**Issue by Stanzilla** [vuejs/vetur#1779]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows 10 2004	
- Vetur version: 0.24.0	
- VS Code version:

```
Version: 1.44.0-insider (system setup)
Commit: efd7548df65de8e775015b67863190e6bd4934fc
Date: 2020-03-13T06:05:25.782Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

## Problem

```
Loaded bundled typescript@3.7.5.
Vetur initialized
c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\server\node_modules\typescript\lib\typescript.js:131068
                throw error;
                ^

Error: Could not find source file: '\\wsl$\Ubuntu\home\stan\projects\personal\WeakAurasCompanion\src\App.vue'.
    at getValidSourceFile (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\server\node_modules\typescript\lib\typescript.js:131064:29)
    at Object.getSyntacticDiagnostics (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\server\node_modules\typescript\lib\typescript.js:131278:52)
    at Object.doValidation (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\server\dist\modes\script\javascript.js:74:32)
    at c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\server\dist\services\vls.js:378:51
    at Array.forEach (<anonymous>)
    at VLS.doValidate (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\server\dist\services\vls.js:376:72)
    at VLS.validateTextDocument (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\server\dist\services\vls.js:370:34)
    at Timeout._onTimeout (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\server\dist\services\vls.js:359:18)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  ProgramFiles: [
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es5.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2016.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.dom.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.core.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.collection.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.generator.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.iterable.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.promise.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.proxy.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.reflect.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.symbol.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2016.array.include.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.object.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.string.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.intl.d.ts',
    'c:/Users/Stan/.vscode-insiders/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts',
    '//wsl$/Ubuntu/home/stan/projects/personal/WeakAurasCompanion/tools/scripts/Utils.ts',
    '//wsl$/Ubuntu/home/stan/projects/personal/WeakAurasCompanion/tools/scripts/Utils.spec.ts',
    '//wsl$/Ubuntu/home/stan/projects/personal/WeakAurasCompanion/tools/scripts/extract-i18n-messages.ts',
    'vue-temp/vue-editor-bridge.ts',
    'ubuntu/home/stan/projects/personal/WeakAurasCompanion/src/App.vue'
  ]
}
[Info  - 17:04:26] Connection to server got closed. Server will restart.
[Error - 17:04:26] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-jsonrpc\lib\main.js:904:25)
	at Object.dispose (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-languageclient\lib\client.js:74:35)
	at LanguageClient.handleConnectionClosed (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-languageclient\lib\client.js:2309:42)
	at LanguageClient.handleConnectionClosed (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-languageclient\lib\main.js:155:15)
	at closeHandler (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-languageclient\lib\client.js:2296:18)
	at CallbackList.invoke (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at closeHandler (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-jsonrpc\lib\main.js:240:26)
	at CallbackList.invoke (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
	at Emitter.fire (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-jsonrpc\lib\events.js:121:36)
	at IPCMessageReader.fireClose (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
	at ChildProcess.<anonymous> (c:\Users\Stan\.vscode-insiders\extensions\octref.vetur-0.24.0\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
	at ChildProcess.emit (events.js:208:15)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 17:04:26] Request textDocument/documentLink failed.
```

## Reproducible Case

Open a Vue project and switch between files

**Comment by yoyo930021** [comment]
The problem may be solve in new version.
https://twitter.com/kazuyukimiyake/status/1336950473765470208?s=20
