### ISSUE TITLE
Crash when using UNC paths.

### ISSUE THREAD

**Issue by ivalkenburg** [vuejs/vetur#1959]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Windows / WSL2
- Vetur version: 0.24.0
- VS Code version: 1.45.1

## Problem

When opening a .vue file in directory which resides in UNC path (network drive or WSL) VLS crashes returning error .vue file could not be found. 

```
[Info  - 5:21:48 AM] Connection to server got closed. Server will restart.
Loaded bundled typescript@3.7.5.
Vetur initialized
c:\Users\Igor\.vscode\extensions\octref.vetur-0.24.0\server\node_modules\typescript\lib\typescript.js:131068
                throw error;
                ^

Error: Could not find source file: '\\wsl$\Development\home\igorv\nuxt-test\pages\index.vue'.
    at getValidSourceFile (c:\Users\Igor\.vscode\extensions\octref.vetur-0.24.0\server\node_modules\typescript\lib\typescript.js:131064:29)
    at Object.getSyntacticDiagnostics (c:\Users\Igor\.vscode\extensions\octref.vetur-0.24.0\server\node_modules\typescript\lib\typescript.js:131278:52)
    at Object.doValidation (c:\Users\Igor\.vscode\extensions\octref.vetur-0.24.0\server\dist\modes\script\javascript.js:74:32)
    at c:\Users\Igor\.vscode\extensions\octref.vetur-0.24.0\server\dist\services\vls.js:378:51
    at Array.forEach (<anonymous>)
    at VLS.doValidate (c:\Users\Igor\.vscode\extensions\octref.vetur-0.24.0\server\dist\services\vls.js:376:72)
    at VLS.validateTextDocument (c:\Users\Igor\.vscode\extensions\octref.vetur-0.24.0\server\dist\services\vls.js:370:34)
    at Timeout._onTimeout (c:\Users\Igor\.vscode\extensions\octref.vetur-0.24.0\server\dist\services\vls.js:359:18)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  ProgramFiles: [
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es5.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2016.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.dom.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.core.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.collection.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.generator.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.iterable.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.promise.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.proxy.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.reflect.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.symbol.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2016.array.include.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.object.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.sharedmemory.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.string.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.intl.d.ts',
    'c:/Users/Igor/.vscode/extensions/octref.vetur-0.24.0/server/node_modules/typescript/lib/lib.es2017.typedarrays.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/vue/types/vnode.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/vue/types/options.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/vue/types/plugin.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/vue/types/vue.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/vue/types/umd.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/vue/types/index.d.ts',
    'vue-temp/vue-editor-bridge.ts',
    'development/home/igorv/nuxt-test/pages/index.vue',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/@types/json-schema/index.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/@types/color-name/index.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/@types/normalize-package-data/index.d.ts',
    '//wsl$/Development/home/igorv/nuxt-test/node_modules/@types/q/index.d.ts'
  ]
}
```

## Reproducible Case

Create .vue file containing javascript in a directory on mapped network drive or wsl container. Open directory in visual studio code and open the .vue file.

**Comment by octref** [comment]
Seems similar to #1779.
