### ISSUE TITLE
Clean up CI output

### ISSUE THREAD

**Issue by octref** [vuejs/vetur#2151]
https://github.com/microsoft/vscode/blob/34dee12ff383689d9d5e62f6b263ed644e4df44d/src/vs/workbench/api/common/extHostTypes.ts#L1012-L1016

Need to validate that all symbols have a `name`

```
name must not be falsy: Error: name must not be falsy
        at Function.validate (/Users/pine/Code/mine/vetur/vetur/.vscode-test/vscode-1.47.3/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:442:18)
        at new x (/Users/pine/Code/mine/vetur/vetur/.vscode-test/vscode-1.47.3/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:441:950)
        at new x (/Users/pine/Code/mine/vetur/vetur/.vscode-test/vscode-1.47.3/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:429:431)
        at asSymbolInformation (/Users/pine/Code/mine/vetur/vetur/node_modules/vscode-languageclient/lib/protocolConverter.js:449:22)
        at /Users/pine/Code/mine/vetur/vetur/node_modules/vscode-languageclient/lib/protocolConverter.js:429:42
        at Array.map (<anonymous>)
        at Object.asSymbolInformations (/Users/pine/Code/mine/vetur/vetur/node_modules/vscode-languageclient/lib/protocolConverter.js:429:23)
        at /Users/pine/Code/mine/vetur/vetur/node_modules/vscode-languageclient/lib/client.js:1088:70
```

This can be turned off with `update.mode: "none"`
```
[main 2020-08-13T05:31:48.191Z] update#setState checking for updates

[main 2020-08-13T05:31:48.989Z] update#setState idle
```

Not sure what to do for this one.

```
stty: stdin isn't a terminal
```

Not sure what to do either. Just filter it out probably.

```
(node:6848) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information
```

**Comment by octref** [comment]
Alright, did what I can do. Will leave the `stty` and Electron one for later.
