### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by zhangweihong** [vuejs/vetur#2276]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 00007FF7C8466DAA VR_GetStringForHmdError+219210
 2: 00007FF7C79F43B6 node::Buffer::New+43430
 3: 00007FF7C79F4423 node::Buffer::New+43539
 4: 00007FF7C64FDFF8 v8::internal::Version::GetVersion+792
 5: 00007FF7C64FDFA1 v8::internal::Version::GetVersion+705
 6: 00007FF7C6689233 v8::Unlocker::~Unlocker+254403
 7: 00007FF7C668FF58 v8::Unlocker::~Unlocker+282344
 8: 00007FF7C6664FD2 v8::Unlocker::~Unlocker+106338
 9: 00007FF7C665E436 v8::Unlocker::~Unlocker+78790
10: 00007FF7C6665DF9 v8::Unlocker::~Unlocker+109961
11: 00007FF7C67CDCBF v8::Platform::SystemClockTimeMillis+510655
12: 00007FF7C6955D49 v8::internal::TickSample::print+177497
13: 00007FF7C6EAAB9C v8_inspector::V8StackTraceId::ToString+2982396
14: 000001C7005CB5CB 
[Info  - 下午4:55:41] Connection to server got closed. Server will restart.
[Error - 下午4:55:41] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:228:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 下午4:55:41] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:228:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 下午4:55:41] Request textDocument/documentLink failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:228:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 下午4:55:41] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:228:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 下午4:55:41] Request textDocument/foldingRange failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:228:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 下午4:55:41] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:904:25)
    at Object.dispose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:74:35)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2309:42)
    at LanguageClient.handleConnectionClosed (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\main.js:155:15)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-languageclient\lib\client.js:2296:18)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at closeHandler (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\main.js:240:26)
    at CallbackList.invoke (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\events.js:121:36)
    at IPCMessageReader.fireClose (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.<anonymous> (c:\Users\whalesunity\.vscode\extensions\octref.vetur-0.27.3\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:228:7)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by yoyo930021** [comment]
Please provide a repro project.
https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

**Comment by zhangweihong** [comment]
![微信截图_20200914170413](https://user-images.githubusercontent.com/6658343/93066355-77075b00-f6ac-11ea-90c1-0f9e493e1b38.png)
![微信截图_20200914170429](https://user-images.githubusercontent.com/6658343/93066364-7969b500-f6ac-11ea-8373-86844b3f29cd.png)

**Comment by zhangweihong** [comment]
![image](https://user-images.githubusercontent.com/6658343/93066426-91d9cf80-f6ac-11ea-98f8-6ec3d2f9df96.png)

**Comment by rchl** [comment]
You are running out of memory. There is no way to tell what's the issue unless you provide a project that reproduces.

**Comment by zhangweihong** [comment]
> You are running out of memory. There is no way to tell what's the issue unless you provide a project that reproduces.

This is the nuxt sample project, which uses the plug-in in vscode, and then reports an out of memory error without any prompt

**Comment by zhangweihong** [comment]
> You are running out of memory. There is no way to tell what's the issue unless you provide a project that reproduces.

It feels like it's caused by errors like memory leaks, or dead loops, and memory keeps growing until it crashes

**Comment by zhangweihong** [comment]
![image](https://user-images.githubusercontent.com/6658343/93097532-49d0a200-f6d8-11ea-9d24-db59c92e99ee.png)

**Comment by zhangweihong** [comment]
> Please provide a repro project.
> https://github.com/vuejs/vetur/blob/master/.github/NO_REPRO_CASE.md

How to ignore vetur to check the files in the static folder?

**Comment by zhangweihong** [comment]
> You are running out of memory. There is no way to tell what's the issue unless you provide a project that reproduces.

How to ignore vetur to check the files in the static folder?

**Comment by rchl** [comment]
I don't think Vetur has any business in processing image files. If it's doing that then it might be a bug. That's why we've asked you to provide a repo that reproduces.

Also, are you sure it's Vetur that uses all the memory? It could be another plugin that does that and that would cause Vetur to also crash due to not having enough memory available.

**Comment by yoyo930021** [comment]
I have a bold guess.
https://github.com/isaacs/node-glob/issues/375

If nuxt sample project can repro, I will study it.
Replace `glob` to `fast-glob` probably.

**Comment by zhangweihong** [comment]
> fast-glob

![image](https://user-images.githubusercontent.com/6658343/93154892-63ed9d00-f737-11ea-8dbb-03fd5b68205a.png)
![image](https://user-images.githubusercontent.com/6658343/93154913-6fd95f00-f737-11ea-8ba0-37c6fb5d2192.png)

It should be the m3u8 format video ‘ts’ file that I used was mistaken for typescript files to cause vetur to compile, now it can only be changed to uppercase suffix TS files, all of which are better, so is there a better way to separate this" static "directory, don't let vetur check it?

**Comment by zhangweihong** [comment]
> I don't think Vetur has any business in processing image files. If it's doing that then it might be a bug. That's why we've asked you to provide a repo that reproduces.
> 
> Also, are you sure it's Vetur that uses all the memory? It could be another plugin that does that and that would cause Vetur to also crash due to not having enough memory available.

It should be the m3u8 format video ‘ts’ file that I used was mistaken for typescript files to cause vetur to compile, now it can only be changed to uppercase suffix TS files, all of which are better, so is there a better way to separate this" static "directory, don't let vetur check it?

**Comment by zhangweihong** [comment]
![image](https://user-images.githubusercontent.com/6658343/93157047-0576ed80-f73c-11ea-9b14-0412feb00fd3.png)

So, it can be used now, aha

**Comment by yoyo930021** [comment]
You can use `tsconfig.json` include exclude options.
https://www.typescriptlang.org/tsconfig#exclude

**Comment by zhangweihong** [comment]
> You can try to use `tsconfig.json` include exclude options.
> https://www.typescriptlang.org/tsconfig#exclude

I tried it but it didn't work
