### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by rjoo** [vuejs/vetur#230]
- Platform: Windows
- Vetur version: 0.7.0
- VSCode version: 1.13.0

With or without a `jsconfig.json` I'm getting this error and a constant need to reload .

````
C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\vueHTML\ls\parser\htmlScanner.js:31
        this.len = source.length;
                         ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\vueHTML\ls\parser\htmlScanner.js:31:26)
    at Object.createScanner (C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\vueHTML\ls\parser\htmlScanner.js:173:18)
    at Object.getDocumentRegions (C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\embeddedSupport.js:8:35)
    at C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\languageModes.js:13:34
    at Object.get (C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\languageModelCache.js:30:33)
    at C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\js\index.js:24:43
    at Object.get (C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\languageModelCache.js:30:33)
    at Object.getScriptKind (C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\modes\js\index.js:87:33)
    at Object.getScriptKind (C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\node_modules\typescript\lib\typescript.js:71447:31)
    at HostCache.createEntry (C:\Users\rossj\.vscode\extensions\octref.vetur-0.7.0\client\server\node_modules\typescript\lib\typescript.js:85852:36)
[Info  - 10:22:55 AM] Connection to server got closed. Server will restart.
vetur initialized
````

**Comment by sotaan** [comment]
Same problem here (well I think so):
```
vetur initialized
[Error - 10:21:22 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:23 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:24 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:24 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:24 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:25 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:38 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:41 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:42 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 10:21:55 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'length' of undefined
  Code: -32603 
/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/vueHTML/ls/parser/htmlScanner.js:31
        this.len = source.length;
                         ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/vueHTML/ls/parser/htmlScanner.js:31:26)
    at Object.createScanner (/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/vueHTML/ls/parser/htmlScanner.js:173:18)
    at Object.getDocumentRegions (/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/embeddedSupport.js:8:35)
    at /Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/languageModes.js:13:34
    at Object.get (/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/languageModelCache.js:30:33)
    at /Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/js/index.js:24:43
    at Object.get (/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/languageModelCache.js:30:33)
    at Object.getScriptKind (/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/modes/js/index.js:87:33)
    at Object.getScriptKind (/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/node_modules/typescript/lib/typescript.js:71447:31)
    at HostCache.createEntry (/Users/david/.vscode/extensions/octref.vetur-0.7.0/client/server/node_modules/typescript/lib/typescript.js:85852:36)
[Info  - 10:21:59 AM] Connection to server got closed. Server will restart.
vetur initialized
```

**Comment by HerringtonDarkholme** [comment]
Can you give an example vue file to reproduce this bug? Thanks!

**Comment by rnenjoy** [comment]
<template>
  <div>
    
  </div>
</template>

<script>
export default {
  name: 'signup',
  data () {
    return {
      signup: {},
      brands: [
        
      ]
    }
  }
}
</script>

<style>
</style>


This gives me this errror

**Comment by octref** [comment]
Are you guys all using Windows by any chance?

@rnenjoy Your case doesn't repro for me.

Please try the latest version. And if this happens, please share with me a repro case, like a repo modified from https://github.com/vuejs-templates/webpack. Otherwise I can't help.

**Comment by rjoo** [comment]
Reinstalled and it seems to work just fine now. Thanks
