### ISSUE TITLE
Vue Language Server crashes on WSL 2

### ISSUE THREAD

**Issue by LeonMrBonnie** [vuejs/vetur#2302]
- [X] I have searched through existing issues
- [X] I have read through [docs](https://vuejs.github.io/vetur)
- [X] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: WSL 2 Ubuntu 20.04 running on Windows 10
- Vetur version: 0.27.3
- VS Code version: 1.49.1

## Problem

When trying to use Vetur on a WSL 2 machine in VSCode, the Vue language server crashes. When I try this on my local Windows 10 machine, it works fine.
Output from Vue Language Server: [Pastebin](https://pastebin.com/4fpGYPpU)

## Reproducible Case

N/A. Any .vue file I open does not work.

**Comment by octref** [comment]
Log is here. I don't have a machine with WSL2. If someone can debug it I'd be grateful.

```
Loaded bundled typescript@4.0.2.
Vetur initialized
[Error - 6:18:00 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Debug Failure. Expected -4384 >= 0
  Code: -32603 
/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:2472
            throw e;
            ^

Error: Debug Failure. Expected -4384 >= 0
    at createFileDiagnostic (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:17987:18)
    at createFileDiagnosticAtReference (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:105040:44)
    at addProgramDiagnosticAtRefPath (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:105050:93)
    at checkSourceFilesBelongToPath (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:104727:25)
    at getCommonSourceDirectory (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:103132:40)
    at verifyCompilerOptions (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:104937:27)
    at Object.createProgram (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:103090:9)
    at synchronizeHostData (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:143900:26)
    at Object.getProgram (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/node_modules/typescript/lib/typescript.js:143992:13)
    at languageServiceIncludesFile (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/server/dist/modes/script/javascript.js:591:26)
[Info  - 6:18:00 PM] Connection to server got closed. Server will restart.
[Error - 6:18:00 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 6:18:00 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 6:18:00 PM] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 6:18:00 PM] Request textDocument/foldingRange failed.
Error: Connection got disposed.
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[Error - 6:18:00 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at LanguageClient.handleConnectionClosed (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at IPCMessageReader.fireClose (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.<anonymous> (/home/leonmrbonnie/.vscode-server/extensions/octref.vetur-0.27.3/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at ChildProcess.emit (events.js:228:7)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by LeonMrBonnie** [comment]
This is now fixed for me in v0.28.0

**Comment by yoyo930021** [comment]
> This is now fixed for me in v0.28.0

You can close this issue when problem no exist.

**Comment by szqingt** [comment]
> > This is now fixed for me in v0.28.0
> 
> You can close this issue when problem no exist.

reappear in v0.33.1 ，i try to use v0.33.0 is ok

**Comment by luvletterldl** [comment]
@szqingt 0.33.0 is not work either.

**Comment by szqingt** [comment]
@luvletterldl I don't know why you can't use it, I have no problem using it. This is my environment information. 

## Info
* Platform: WSL 2 Ubuntu 20.04 running on Windows 10(18363)
* Vetur version: 0.33.0
* VS Code version: 1.54.3

**Comment by pbajr** [comment]
I'm encounteing this issue on version 0.35.0

 - WSL2 Ubuntu 20
 - Version 0.35.0
 - VSCode Version 1.64.2

<img width="1905" alt="image" src="https://user-images.githubusercontent.com/7844463/155515240-a7eb3880-677e-451f-8725-77d84f345d00.png">

**Comment by pbajr** [comment]
Finally I was able to figure out what is going on

So I tried to Trace Server > Vue Language Server

<img width="1855" alt="image" src="https://user-images.githubusercontent.com/7844463/156227821-281a5655-5b81-472c-ac14-8be280b3cc13.png">

Then along the way I'm getting
```
 JavaScript heap out of memory
```

So the solution was to increase memory of nodejs, you can put this on bashrc or zshrc. Maybe its up to you on how much space you want

```
export NODE_OPTIONS="--max-old-space-size=8192"
```

<img width="1769" alt="image" src="https://user-images.githubusercontent.com/7844463/156228330-473a0df6-9f0f-43ab-9c52-64a8ac81949b.png">

Cheers
