### ISSUE TITLE
Undefined valueDeclaration in props is crashing vls

### ISSUE THREAD

**Issue by javiertury** [vuejs/vetur#2367]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform:  Linux
- Vetur version: vls 0.5.4
- VS Code version: Coc-vetur 1.2.0

## Problem

Vetur is continuously crashing because `s.valueDeclaration` can be `undefined` here:

https://github.com/vuejs/vetur/blob/a7331253140367075e841268bbcc3a2b06ec04df/server/src/modes/script/componentInfo.ts#L322-L324

```
<project-path>/node_modules/typescript/lib/typescript.js:26110
        return node.kind === 285 /* PropertyAssignment */;
                    ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isPropertyAssignment (<project-path>/node_modules/typescript/lib/typescript.js:26110:21)
    at .../coc-vetur/node_modules/vls/dist/modes/script/componentInfo.js:246:41
    at Array.map (<anonymous>)
    at getObjectProps (.../coc-vetur/node_modules/vls/dist/modes/script/componentInfo.js:245:59)
    at getClassAndObjectInfo (.../coc-vetur/node_modules/vls/dist/modes/script/componentInfo.js:463:35)
    at getProps (.../coc-vetur/node_modules/vls/dist/modes/script/componentInfo.js:65:60)
    at analyzeDefaultExportExpr (.../coc-vetur/node_modules/vls/dist/modes/script/componentInfo.js:39:19)
    at .../coc-vetur/node_modules/vls/dist/modes/script/componentInfo.js:29:45
    at Array.forEach (<anonymous>)
    at Object.getComponentInfo (.../coc-vetur/node_modules/vls/dist/modes/script/componentInfo.js:24:33)
```

I propose to use instead

```
                const status = s.valueDeclaration !== undefined && tsModule.isPropertyAssignment(s.valueDeclaration)
                    ? getPropValidatorInfo(s.valueDeclaration.initializer)
                    : { hasObjectValidator: false, required: true };
```

## Reproducible Case

Debugging the issue the problem is the line `value: T | undefined` (obtained from `s.declarations[0].getText()`). This line is part of the following fragment.

```
type Base = Record<string, unknown>;

export type Props <T extends Base = Base> = {
  value: T | undefined
};
```

Later this type is used to build properties:

```
// Helper
export type PropsOptions <Props> = {
  [K in keyof Props]: PropOptions<Props[K]>
};

// Properties options
const props: PropOptions<Props<Resource>> = {
  value: {
     type: Object as () => Resource | undefined,
     default: undefined
  }
};

// Component
export default defineComponent({
  props,
  setup(props, { root: { $router } }) {
     ...
  }
});
```

And also used in parents to create an object of properties that will be binded to the component.

```
// In parent component, script
const resourceProps: Props<Resource> = {
  value: resource
};

// In parent component, template
v-bind="resourceProps"
```

EDIT: fix code typo

**Comment by yoyo930021** [comment]
I don't think it's legal to write in `vue.js`.

The right way:
```typescript
import { PropType } from 'vue'

// Properties options
const props = {
  value: {
     type: Function as PropType<() => Reource | undefined>,
     required: false
  }
};

// Component
export default defineComponent({
  props,
  setup(props, { root: { $router } }) {
     ...
  }
});
```

But I agree we need to deal with this crash.

**Comment by javiertury** [comment]
Before vetur gained support to check properties in templates, the scheme above was the only way to reliably check property types in both parent and child components.

But now I agree, the scheme I used above should not be used.
