### ISSUE TITLE
Autocompletion incredible slow for easy tasks since VSC July 2021 update 

### ISSUE THREAD

**Issue by flashspys** [vuejs/vetur#3113]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform: MacOS and Linux
- Vetur version: 0.34.1
- VS Code version: 1.59.0

## Problem

We have a quite large Vue 2 project, most parts in typescript. The code completion on very easy types (e.g. a simple string array) is very slow. A cpu profile is attached. Its quite a mess to view, I can't read a lot from it. In this profile I invoked code completion on an array. It took about 15s to complete. 
[CPU-20210816T144628.cpuprofile.zip](https://github.com/vuejs/vetur/files/6992426/CPU-20210816T144628.cpuprofile.zip)

The vue-language-server outputs very often 
```
[Error - 2:41:08 PM] Request textDocument/semanticTokens/range failed.
  Message: Request textDocument/semanticTokens/range failed with message: Cannot read property 'flags' of undefined
  Code: -32603 
```

Please let me know if you need further information.

**Comment by dorian-marchal** [comment]
Same issue but for a Vue 2 project in JS (not TS).
Saving takes up to 8 seconds in a ~300 lines single file component.

**Comment by douglasg14b** [comment]
Same issue here, sometimes take MINUTES with TS components.

**Comment by douglasg14b** [comment]
More verbose log entries look like:

> [2021-12-14 16:00:22.973] [renderer1] [error] Request textDocument/semanticTokens/full failed with message: Cannot read property 'flags' of undefined: Error: Request textDocument/semanticTokens/full failed with message: Cannot read property 'flags' of undefined
	at c:\Users\Douglas\.vscode\extensions\octref.vetur-0.35.0\dist\vueMain.js:1:64858
	at c:\Users\Douglas\.vscode\extensions\octref.vetur-0.35.0\dist\vueMain.js:1:65153
	at Immediate.<anonymous> (c:\Users\Douglas\.vscode\extensions\octref.vetur-0.35.0\dist\vueMain.js:1:65518)
	at processImmediate (internal/timers.js:461:21)

**Comment by douglasg14b** [comment]
Perhaps this should be a bug, and not perf @yoyo930021?

**Comment by douglasg14b** [comment]
Well, if I just return early if `!parentSymbol` I actually get auto-completion again, it's just ~10s or so per auto-completion. So that's progress at least...
