### ISSUE TITLE
prettier-eslint format failed  --  TypeError: (0 , cgt.default) is not a function

### ISSUE THREAD

**Issue by rushive** [vuejs/vetur#3168]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://vuejs.github.io/vetur/guide/FAQ.html)
- [x] I have tried restarting VS Code or running `Vetur: Restart VLS`

## Info

- Platform:  windows10 1909
- Vetur version: 0.34.1
- VS Code version: 1.60.2

## Problem

When I use `eslint-config-standard` or `eslint-config-airbnb` as extends of eslint and right click `format document`, it threw the error:
```
Prettier-Eslint format failed
[Error] TypeError: (0 , lgt.default) is not a function
    at extractRuleValue (<user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:57:25)
    at getRuleValue (<user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:63:143)
    at ruleValue (<user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:54:23527)
    at configureOptions (<user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:54:24907)
    at <user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:54:24731
    at Array.reduce (<anonymous>)
    at getPrettierOptionsFromESLintRules (<user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:54:24717)
    at getOptionsForFormatting (<user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:54:24044)
    at format (<user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:75:1807)
    at prettierEslintify (<user>\.vscode\extensions\octref.vetur-0.34.0\server\dist\vls.js:642:30)
```

And `0.34.0` also gave me an same error, but `0.33.1` and below work well. It seems broken after 0.34.0 release.

I also try to run `eslint --fix` separately and it can lint the code normally.

## Reproducible Case

[this](https://github.com/crimsonmoon9/report-sample-repo)

**Comment by crimsonmoon9** [comment]
> Do you open `vetur.useWorkspaceDependencies` ?

Thanks, this works for me after open it.
Would you open this option by default ? Some bundled packages seem not to be fully support until install newer ones manually.
