### ISSUE TITLE
vetur crashed when opening vue project

### ISSUE THREAD

**Issue by superlbr** [vuejs/vetur#343]
- [Y] I searched through existing issues.
- [Y] I have looked through docs at https://vuejs.github.io/vetur/

## Info

- Platform: macOS 10.12.5
- Vetur version: 0.91
- VSCode version: 1.14.1

## Reproducible Case
    1. When I open vue project, It just crashed.
    2. While vux project actually, even I reinstall vetur.
    3. And I did't install other vue extension.

  

###
/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:7990
    function isRequireCall(callExpression, checkArgumentIsStringLiteral) {
                          ^

RangeError: Maximum call stack size exceeded
    at Object.isRequireCall (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:7990:27)
    at collectDynamicImportOrRequireCalls (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:70151:24)
    at visitNode (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:15944:20)
    at Object.forEachChild (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:16114:24)
    at collectDynamicImportOrRequireCalls (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:70158:24)
    at visitNode (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:15944:20)
    at Object.forEachChild (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:16114:24)
    at collectDynamicImportOrRequireCalls (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:70158:24)
    at visitNode (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:15944:20)
    at Object.forEachChild (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vue-language-server/node_modules/typescript/lib/typescript.js:16114:24)
[Info  - 9:27:10 AM] Connection to server got closed. Server will restart.
[Error - 9:27:10 AM] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-jsonrpc/lib/main.js:816:25)
    at Object.dispose (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-languageclient/lib/client.js:66:35)
    at LanguageClient.handleConnectionClosed (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-languageclient/lib/client.js:1071:38)
    at LanguageClient.handleConnectionClosed (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-languageclient/lib/main.js:86:15)
    at closeHandler (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-languageclient/lib/client.js:1059:18)
    at CallbackList.invoke (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at closeHandler (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-jsonrpc/lib/main.js:212:26)
    at CallbackList.invoke (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at IPCMessageReader.AbstractMessageReader.fireClose (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-jsonrpc/lib/messageReader.js:126:27)
    at ChildProcess.<anonymous> (/Users/dva/.vscode/extensions/octref.vetur-0.9.1/client/node_modules/vscode-jsonrpc/lib/messageReader.js:244:61)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)

    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by octref** [comment]
![image](https://user-images.githubusercontent.com/4033249/28346907-87193550-6c66-11e7-8024-92a02ff0409d.png)

https://vuejs.github.io/vetur/setup.html

**Comment by octref** [comment]
And https://github.com/vuejs/vetur/issues/216#issuecomment-315608474
