### ISSUE TITLE
formatting for .vue files not work

### ISSUE THREAD

**Issue by haoranw** [vuejs/vetur#409]
## Info

- Platform: macOS 10.12.6
- Vetur version: 0.9.5
- VSCode version: 1.15.1

## Problem

The fromatting does not work on my computer.
I have uninstalled vscode and reinstall it ,only add one plugin-vetur,but still not work.

**Comment by haoranw** [comment]
one of my projects use vue1.x , i can use format in this project.
but another project that build with  vue2,it's not ok

**Comment by haoranw** [comment]
find that when I open the vue2 project,there will come out a error msg :"The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."

**Comment by haoranw** [comment]
it work after i add jsconfig.json  file in my peoject

**Comment by haoranw** [comment]
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 Connection got disposed.: Error: Connection got disposed.
    at Object.dispose (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-jsonrpc/lib/main.js:816:25)
    at Object.dispose (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-languageclient/lib/client.js:66:35)
    at LanguageClient.handleConnectionClosed (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-languageclient/lib/client.js:1071:38)
    at LanguageClient.handleConnectionClosed (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-languageclient/lib/main.js:86:15)
    at closeHandler (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-languageclient/lib/client.js:1059:18)
    at CallbackList.invoke (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at closeHandler (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-jsonrpc/lib/main.js:212:26)
    at CallbackList.invoke (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at IPCMessageReader.AbstractMessageReader.fireClose (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-jsonrpc/lib/messageReader.js:126:27)
    at ChildProcess.<anonymous> (/Users/wang/.vscode/extensions/octref.vetur-0.9.5/client/node_modules/vscode-jsonrpc/lib/messageReader.js:244:61)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)

**Comment by HerringtonDarkholme** [comment]
Hi, can you provide a reproducing repo? 

Or can you try opening https://github.com/octref/veturpack?

**Comment by haoranw** [comment]
sorry,it's one of my bussiness project
once I open this project ,there will come out a error msg :"The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted." 
The others projects work well . Is this problem associate with project files number or size?

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/blob/master/docs/setup.md

Try including only source file. 3rd party libraries or compiled code are usually culprits.

**Comment by haoranw** [comment]
it works,thx!
