### ISSUE TITLE
Vue Language Server crash on VsCode 1.17.0

### ISSUE THREAD

**Issue by vladzur** [vuejs/vetur#464]
## Info

- Platform: Linux
- Vetur version: 0.9.11
- VSCode version: 1.17.0

## Problem

```
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vladzur/.vscode/extensions/octref.vetur-0.9.11/client/node_modules/vue-language-server/dist/modes/style/index.js:5:11)
    at Object.<anonymous> (/home/vladzur/.vscode/extensions/octref.vetur-0.9.11/client/node_modules/vue-language-server/dist/modes/style/index.js:140:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 10:38:17] Connection to server got closed. Server will not be restarted.
```

**Comment by vladzur** [comment]
I manualy update dependencies
