### ISSUE TITLE
The Vue Language Server server crashed

### ISSUE THREAD

**Issue by rathesDot** [vuejs/vetur#526]
## Info

- Platform: macOS High Sierra 10.13.1
- Vetur version: 0.11.0
- VS Code version: 1.18.0

## Problem

When running VS Code I get the following Error:

`The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.`

After that I can't use the vue related snippets, while things like highlighting does work.

That's the output of the Vue Language Server:

```
Error: Cannot find module '@emmetio/extract-abbreviation'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rathessachchithananthan/.vscode/extensions/octref.vetur-0.11.0/client/node_modules/vscode-emmet-helper/out/emmetHelper.js:9:17)
    at Object.<anonymous> (/Users/rathessachchithananthan/.vscode/extensions/octref.vetur-0.11.0/client/node_modules/vscode-emmet-helper/out/emmetHelper.js:640:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 10:17:04] Connection to server got closed. Server will not be restarted.

```

That's been thrown three times.

## Reproducible Case

Don't know how to reproduce. I do not even have this problem in my Windows machine, just on macOS.

Even when I start a simple `vue init webpack myproject` and open up VS Code I get this error.

**Comment by HerringtonDarkholme** [comment]
https://github.com/vuejs/vetur/wiki/FAQ#vetur-crash

**Comment by octref** [comment]
Go to `/Users/rathessachchithananthan/.vscode/extensions/octref.vetur-0.11.0/client` and run `npm i` or `yarn`.

VS Code seems to have trouble updating extension dependencies...
