### ISSUE TITLE
 server directory is absent from most recent build on VSCode Marketplace

### ISSUE THREAD

**Issue by superhawk610** [vuejs/vetur#572]
- [ x ] I have searched through existing issues
- [ x ] I have read through [docs](https://vuejs.github.io/vetur)
- [ x ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: Win (Git Bash)
- Vetur version: 0.11.3
- VS Code version: 1.19.0-insider (commit ...07e4)

## Problem

`server` directory is absent from most recent build on VSCode Marketplace:

```shell
super@AaronXPS9560 MINGW64 ~/.vscode-insiders/extensions/octref.vetur-0.11.3
$ ls -l
total 60
drwxr-xr-x 1 super 197609     0 Dec  5 13:46 asset/
drwxr-xr-x 1 super 197609     0 Dec  5 13:46 build/
-rw-r--r-- 1 super 197609 13453 Dec  5 13:46 CHANGELOG.md
drwxr-xr-x 1 super 197609     0 Dec  5 13:46 client/
drwxr-xr-x 1 super 197609     0 Dec  5 13:46 docs/
drwxr-xr-x 1 super 197609     0 Dec  5 13:46 languages/
-rw-r--r-- 1 super 197609  1064 Dec  5 13:46 LICENSE.txt
-rw-r--r-- 1 super 197609  7307 Dec  5 13:46 package.json
-rw-r--r-- 1 super 197609  1627 Dec  5 13:46 README.md
drwxr-xr-x 1 super 197609     0 Dec  5 13:46 syntaxes/
-rw-r--r-- 1 super 197609   861 Dec  5 13:46 tslint.json
-rw-r--r-- 1 super 197609  6652 Dec  5 13:46 yarn.lock
```

This causes the Vue language server to crash with the following error:

```shell
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\super\.vscode-insiders\extensions\octref.vetur-0.11.3\server\dist\vueServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (C:\Users\super\.vscode-insiders\extensions\octref.vetur-0.11.3\client\node_modules\vscode-languageclient\lib\utils\electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
```

## Reproducible Case

1) Install vetur from within VSCode via the Extensions interface.
2) Open a file with the .vue extension.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/568

Use stable for now. I'll include server for next release.
