### ISSUE TITLE
怎么找到octref.vetur-0.11.3下的server目录？

### ISSUE THREAD

**Issue by bianlin** [vuejs/vetur#573]
## Info

- Platform: macOS
- Vetur version: 0.11.3
- VS Code version: 1.19.0-insider

## Problem

Debugger listening on port 6005.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:6005/f1a623ff-9d58-4945-8ae6-2ec46ad23a1d
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/bianlin/.vscode-insiders/extensions/octref.vetur-0.11.3/server/dist/vueServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (/Users/bianlin/.vscode-insiders/extensions/octref.vetur-0.11.3/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Info  - 15:00:19] Connection to server got closed. Server will restart.
Debugger listening on port 6005.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:6005/1ab41303-376e-4fda-bbef-cdce5bbc963d
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/bianlin/.vscode-insiders/extensions/octref.vetur-0.11.3/server/dist/vueServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (/Users/bianlin/.vscode-insiders/extensions/octref.vetur-0.11.3/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Info  - 15:00:19] Connection to server got closed. Server will restart.
Debugger listening on port 6005.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:6005/59ce3be6-2ad3-4c08-a9b4-919a39851583
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/bianlin/.vscode-insiders/extensions/octref.vetur-0.11.3/server/dist/vueServerMain.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Server.<anonymous> (/Users/bianlin/.vscode-insiders/extensions/octref.vetur-0.11.3/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js:110:9)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:191:7)
    at Pipe.onconnection (net.js:1486:8)
[Error - 15:00:19] Connection to server got closed. Server will not be restarted.

**Comment by octref** [comment]
https://github.com/vuejs/vetur/issues/568
