### ISSUE TITLE
Connection got disposed when mixing .js/.vue files

### ISSUE THREAD

**Issue by Robula** [vuejs/vetur#576]
## Info

- Platform: macOS High Sierra
- Vetur version: 0.11.3 - 0.11.5
- VS Code version: 1.18.1 - 1.19.0

## Problem

After launching VSCode and opening a .vue file I get an error in the Developer Tools.
```
[octref.vetur] Connection got disposed.: Error: Connection got disposed.
	at Object.dispose (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-jsonrpc/lib/main.js:816:25)
	at Object.dispose (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-languageclient/lib/client.js:57:35)
	at LanguageClient.handleConnectionClosed (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-languageclient/lib/client.js:1856:38)
	at LanguageClient.handleConnectionClosed (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-languageclient/lib/main.js:78:15)
	at closeHandler (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-languageclient/lib/client.js:1844:18)
	at CallbackList.invoke (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-jsonrpc/lib/main.js:212:26)
	at CallbackList.invoke (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.3/client/node_modules/vscode-jsonrpc/lib/events.js:135:36)
```
![screen shot 2017-12-14 at 10 14 35](https://user-images.githubusercontent.com/15246425/33987108-9d5e0eba-e0b7-11e7-9213-643d85894fde.png)

## Reproducible Case

If I create a new Vue file with basic content and then add a JS file to `src`, upon reloading VSCode I get the above error.

**Comment by HerringtonDarkholme** [comment]
Can you reproduce it in veturpack? https://github.com/octref/veturpack

**Comment by Robula** [comment]
Hi @HerringtonDarkholme, thank you for the reply.

Not quite, I cloned the repisitory and opened VSCode with all but Vetur extension enabled. When I open `client/components/App.vue` I get an exception although different from the first.

```
Language client is not ready yet: Error: Language client is not ready yet
	at LanguageClient.sendRequest (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.5/client/node_modules/vscode-languageclient/lib/client.js:1473:19)
	at Object.provideDocumentColors (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.5/client/out/vueMain.js:76:31)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:444235
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92953
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:72291)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:92916)
	at e.provideColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:444189)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:452573
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:445314)
	at e.$provideDocumentColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:4:452535)
```

![screen shot 2017-12-15 at 08 36 14](https://user-images.githubusercontent.com/15246425/34033743-5d350b24-e173-11e7-85de-950a4b9e15b6.png)

Many thanks

**Comment by Robula** [comment]
VSCode has just updated to 1.19.0 and everything is working as expected now. Thank you.

**Comment by Robula** [comment]
My mistake, the issue is still occurring. The exceptions seen above have now become `Information` in the Developer Tools..
```
  ERR Language client is not ready yet: Error: Language client is not ready yet
	at LanguageClient.sendRequest (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.5/client/node_modules/vscode-languageclient/lib/client.js:1473:19)
	at Object.provideDocumentColors (/Users/robfinbow/.vscode/extensions/octref.vetur-0.11.5/client/out/vueMain.js:76:31)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:449:961
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:93:1004
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:234)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:93:967)
	at e.provideColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:449:915)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:458:253
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:24)
	at e.$provideDocumentColors (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:458:215)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:156 WARNING: Promise with no error callback:11
```
