### ISSUE TITLE
the vue language server server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by CCCMeng** [vuejs/vetur#581]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: windows 10
- Vetur version: 0.11.4
- VS Code version: 1.19.0

## Problem

[Info  - 10:42:04] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^

Error: Cannot find module 'vscode-languageserver'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Administrator\.vscode\extensions\octref.vetur-0.11.4\server\dist\vueServerMain.js:3:33)
    at Object.<anonymous> (C:\Users\Administrator\.vscode\extensions\octref.vetur-0.11.4\server\dist\vueServerMain.js:162:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 10:42:04] Connection to server got closed. Server will not be restarted.

The problem is happend when I updated the lastest vscode.
Is that cause by the vscode version ?

**Comment by henyuan** [comment]
Uninstall the plug-in and reinstall it, I solved this.

**Comment by HerringtonDarkholme** [comment]
Please read our FAQ. https://github.com/vuejs/vetur/blob/master/docs/FAQ.md#vetur-crash
