### ISSUE TITLE
how to debug vue+typescript project create by vuecli3 ?

### ISSUE THREAD

**Issue by xxbld** [vuejs/vetur#908]
vscode

i can breakpoint into *.ts file ,but *.vue unsupport !

launch.json like this:
{
"version": "0.2.0",
"configurations": [
{
"type": "chrome",
"request": "launch",
"name": "vuejs: chrome",
"url": "http://localhost:8080",
"webRoot": "${workspaceFolder}/src",
"breakOnLoad": true,
"sourceMapPathOverrides": {
"webpack:///src/": "${webRoot}/"
}
}
]
}

**Comment by duylddev** [comment]
i'm stuck here too :(

**Comment by octref** [comment]
https://github.com/Microsoft/VSCode-recipes/tree/master/vuejs-cli

You should open issues there.

**Comment by michael-hawker** [comment]
@octref I'm not sure if this is just a documentation issue.  I generated a TypeScript class Vue project with vue-cli, followed the recipe setup, set a breakpoint in the TS in the `script` block of the `Vue` file, and after launching the debugger, I get this message in the debug output about not being able to find a breakpoint I set:

```
******** Unhandled error in debug adapter - Unhandled promise rejection: Error: Could not resolve breakpoint
    at Client.processMessage (c:\Users\user\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:66:36)
    at LoggingSocket.Client.socket.on (c:\Users\user\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:42:48)
    at LoggingSocket.emit (events.js:187:15)
    at Receiver.receiverOnMessage (c:\Users\user\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\websocket.js:742:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (c:\Users\user\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\receiver.js:417:14)
    at perMessageDeflate.decompress (c:\Users\user\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\receiver.js:374:23)
    at _decompress (c:\Users\user\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\permessage-deflate.js:298:9)
    at _inflate.flush (c:\Users\user\.vscode\extensions\msjsdiag.debugger-for-chrome-4.11.2\node_modules\ws\lib\permessage-deflate.js:376:7)
    at afterWrite (_stream_writable.js:480:3)
```

**Comment by Patcher56** [comment]
@michael-hawker I don't think this is a vetur issue. From your log it says the error appears in the `msjsdiag.debugger-for-chrome-4.11.2` extension. So please [open an issue there](https://github.com/microsoft/vscode-chrome-debug/issues).

**Comment by JackLeEmmerdeur** [comment]
As the [docs](https://github.com/Microsoft/vscode-chrome-debug#sourcemaps) of the extension point out, it needs sourcemaps. You possibly need to modify the webpack-config. In a vue-cli-project this is not done via the webpack.config.js.

Instead create the file vue.config.js in the projects root folder and put this inside:

<pre><code>
module.exports = {
    productionSourceMap: false,
    configureWebpack: {
        "devtool": "source-map"
    }
}
</code></pre>

The `productionSourceMap` value configures the vue project to not produce source-maps for a production build (see [here](https://cli.vuejs.org/config/#productionsourcemap)).

Within the `configureWebpack` object, you can amend the webpack-config and `devtool` specifies what type of sourcemaps are produced as stated in the [webpack-docs](https://webpack.js.org/configuration/devtool/). 

I supose if this is missing, that no sourcemaps are produced in debug sessions.
