### ISSUE TITLE
Vetur crashed on jsdoc

### ISSUE THREAD

**Issue by dimensi** [vuejs/vetur#965]
- [x] I have searched through existing issues
- [x] I have read through [docs](https://vuejs.github.io/vetur)
- [x] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

## Info

- Platform: macos
- Vetur version: 0.13
- VS Code version: 1.29

## Problem

```
Vetur initialized
[Error - 1:21:41 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: Debug Failure. Found typedef tag attached to node which it should not be!
  Code: -32603 
/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:4238
            throw e;
            ^

Error: Debug Failure. Found typedef tag attached to node which it should not be!
    at nameForNamelessJSDocTypedef (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:12345:26)
    at getNameOfJSDocTypedef (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:12353:36)
    at Object.getNameOfDeclaration (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:12389:24)
    at Object.hasDynamicName (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:10388:23)
    at declareSymbol (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:21097:33)
    at declareModuleMember (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:21231:28)
    at bindBlockScopedDeclaration (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:22381:25)
    at bindWorker (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:22807:32)
    at bind (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:22558:13)
    at bindJSDocTypedefTagIfAny (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/server/node_modules/typescript/lib/typescript.js:22595:25)
[Error - 1:21:42 PM] Connection to server got closed. Server will not be restarted.
[Error - 1:21:42 PM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-languageclient/lib/client.js:2143:42)
	at LanguageClient.handleConnectionClosed (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-languageclient/lib/client.js:2130:18)
	at CallbackList.invoke (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.IPCMessageReader.eventEmitter.on (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at emitTwo (events.js:131:20)
	at ChildProcess.emit (events.js:214:7)
	at maybeClose (internal/child_process.js:925:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
[Error - 1:21:42 PM] Request textDocument/colorPresentation failed.
Error: Connection got disposed.
	at Object.dispose (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/main.js:876:25)
	at Object.dispose (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-languageclient/lib/client.js:71:35)
	at LanguageClient.handleConnectionClosed (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-languageclient/lib/client.js:2143:42)
	at LanguageClient.handleConnectionClosed (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-languageclient/lib/main.js:150:15)
	at closeHandler (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-languageclient/lib/client.js:2130:18)
	at CallbackList.invoke (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at closeHandler (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/main.js:226:26)
	at CallbackList.invoke (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/events.js:120:36)
	at IPCMessageReader.fireClose (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at ChildProcess.IPCMessageReader.eventEmitter.on (/Users/dimensi/.vscode/extensions/octref.vetur-0.13.0/node_modules/vscode-jsonrpc/lib/messageReader.js:213:45)
	at emitTwo (events.js:131:20)
	at ChildProcess.emit (events.js:214:7)
	at maybeClose (internal/child_process.js:925:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

## Reproducible Case
Write this code
```
<template>
  <div :class="$style.AppList"></div>
</template>

<script>
/**
 * @typedef {object} Item
 * @prop {string?} title
 * @prop {string} desc
 * @prop {string} icon
 */

export default {
  name: "AppList",
  props: {
    /** @type {Item} */
    list: Array
  }
};
</script>

<style lang="stylus" module>
.AppList
  display block
</style>
```
P.S. after restart vscode bug disappear

**Comment by octref** [comment]
I wrote this code in latest development branch, and it doesn't seem to crash any more.

> P.S. after restart vscode bug disappear

**Comment by robertracz** [comment]
Hey guys! Try importing a typedef:

`/** @typedef {typeof import('http')} http*/`

it throws the same error right away
